tests:
  build: .
  command: bash -c "cd /app && activator test"

master:
  image: singularities/spark
  command: start-spark master
  hostname: master
  ports:
    - "6066:6066"
    - "7070:7070"
    - "8080:8080"
    - "50070:50070"

worker:
  image: singularities/spark
  command: start-spark worker master
  environment:
    SPARK_WORKER_CORES: 1
    SPARK_WORKER_MEMORY: 2g
  links:
    - master
